import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/queryProvider";
import { Toaster } from "sonner";
import AuthProvider from "@/components/authProvider";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import ProgressBar from "@/components/progressBar";
import { ThemeProvider } from "@/components/theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <QueryProvider>
        <TooltipProvider>
          <html lang="en">
            <body className={`${inter.className} font-SPR-Regular`}>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
              >
                <ProgressBar>{children}</ProgressBar>
                <Toaster />
              </ThemeProvider>
            </body>
          </html>
        </TooltipProvider>
      </QueryProvider>
    </AuthProvider>
  );
}
